app_ver: "1.5.1" #not good
fr_engine: 'pv' #default, could be pv or cv
time_zone: 'America/New_York'
#dev subscription. I have 16. Obviously not for production
subscription_username: "brightblade42"
subscription_password: "R2y1a1n@"
#credentials required to pull our images
docker_login: "eyemetricfr"
docker_pwd: "19darkangel84"
docker_registry: "docker.io"
env: "dev"

local_ip: '{{ ansible_host }}'
host_ip: '{{ ansible_host }}'
#user we used to ssh into the remote machine. This should always be eyemetric if possible.
master_user: 'brightblade42'
master_pwd: 'Eyemetrc#'
eyemetric_user: 'eyemetric'
eyemetric_group: "eyemetric"
eyemetric_pwd: 'Eyemetr1c#'
#eyemetric_pwd: 'Eyemetr1c#1'
ssh_key_file: "/Users/ryan/.ssh/id_rsa.pub"
#tpass_svc: "https://devsys01.tpassvms.com/tpassservice/"
tpass_svc: "https://devsys01.tpassvms.com/TpassPVService/"
tpass_user: "admin"
tpass_pwd: "njbs1968"

tz: "America/New_York"
pg_ver: "14.1"
app_dir: "/opt/eyemetric/fr"
cert_dir: '{{app_dir}}/certs'
# don't overwrite any existing volumes.
overwrite_data_volumes: false

################################################
# pv processor
################################################
pv_http_interface: "on"
pv_inference_workers: 1
pv_proc_port_1: 50051
pv_proc_port_2: 8081


################################################
# pv identity
################################################
pv_pg_user: "admin"
pv_pg_pwd: "admin"
pv_db_name: "identity"
postgres_uri: "postgresql://{{pv_pg_user }}:{{ pv_pg_pwd }}@{{ local_ip }}:5432/{{ pv_db_name }}?sslmode=disable"
http_proxy: "on"
pv_ident_port_1: 5656
pv_ident_port_2: 8080

################################################
# streaming
################################################
PV_INFERENCE_WORKERS: 1
PV_POSTPROCESSOR_WORKERS: 1
PV_OUTPUT_FACES_ONLY: True
PV_FACE_QUALITY_TRACKING: 0.50
#NVIDIA_VISIBLE_DEVICES=all
#NVIDIA_DRIVER_CAPABILITIES=all


################################################
# List of OCI images representing our application
################################################


dbdata_image: 'docker.io/eyemetricfr/dbdata:{{ app_ver }}'

