---
# vars file for paravision-v6
pv_login: "eyemetric_eyemetricfr"
pv_pwd: "R2y1a1n@"
pv_registry: "containers.paravision.ai"

gpu_images:
    pvdb: "{{docker_registry}}/postgres/postgres:12.0"
    processor: "{{docker_registry}}/processor/processor:v6-gen5-balanced-tensorrt"
    identity: "docker.io/eyemetricfr/identity:v4.0.0"
    streaming: "{{docker_registry}}/streaming/streaming:v6.0.0-tensorrt"

cpu_images:
    pvdb: "{{docker_registry}}/postgres/postgres:12.0"
    processor: "{{docker_registry}}/processor/processor:v6-gen5-balanced-openvino"
    identity: "docker.io/eyemetricfr/identity:v4.0.0"
    streaming: "{{docker_registry}}/streamqing/streaming:v6-openvino"
