---


# ------------------------
# Create eyemetric user and group if needed
# ------------------------
- name: Create FR accounts
  hosts: all
  remote_user: "{{ eyemetric_user }}"
  #remote_user: tempadmin
  become: yes

  tasks:
    - name: create users
      include_tasks: tasks/create_user_tasks.yml
#     - name: rhel subscription
#       include_tasks: tasks/redhat_sub.yml
  tags:
    - create_user
# ------------------------
# GPU prequisite install play
# ------------------------
- name: Setup NVIDIA for GPU enabled servers
  hosts: gpu
  remote_user: "{{ eyemetric_user }}"
  become: yes

  tasks:
    - name: Print a message
      debug:
        msg: "This would install all the CUDA and nvidia drivers"


#------------------------
# OCI PLAY
#----------------------------
- name: OCI roles
  hosts: all
  become: yes
  remote_user: "{{ eyemetric_user }}"

  pre_tasks:
    - name: Enable RHEL 8 | 9  repos
      include_tasks: tasks/enable_rhel_repo_tasks.yml
      when: ansible_distribution == "RedHat"

  roles:
    - { role: podman,  when: ansible_distribution == "RedHat" }
  tags:
    - oci
# - name: docker role for rhel
#   hosts: all
#   remote_user: "{{ eyemetric_user }}"
#   roles:
#     - { role: docker, when: ansible_distribution == "Ubuntu" }



# ------------------------
# DATA PLAY not sure this is the right place for this
# ------------------------
- name: Install initial data volumes for new installs
  hosts: all
  remote_user: "{{ eyemetric_user }}"
  become: yes
  pre_tasks:
    - name: create app dir directory structure
      file:
        path: '{{ item }}'
        state: directory
        owner: '{{ eyemetric_user }}'
        group: '{{ eyemetric_user }}'
        recurse: true
      loop:
        - '{{ app_dir }}/cpu'
        - '{{ app_dir }}/gpu'
        - '{{ app_dir }}/data'
        - '{{ app_dir }}/certs'
        - '{{ app_dir }}/scripts'
        - '{{ app_dir }}/utils'

  tasks:
    - name: Run the data tasks
      include_tasks: tasks/dbtasks.yml

  tags:
    - oci

# ------------------------
# SAFR 1.5 PLAY
# ------------------------
- name: Install SAFR v1.5 services and dependencies.
  hosts: all
  remote_user: "{{ eyemetric_user }}"
  become: yes


  roles:
    - role: safr-v1_5

  post_tasks:
    - name: Print a message
      debug:
        msg: "Running post tasks for Safr Play"

# ------------------------
# FR ENGINE PLAYS
# ------------------------

- name: Install Paravision (v6) services
  hosts: paravision
  remote_user: "{{ eyemetric_user }}"
  become: yes

  roles:
    - role: paravision-v6
  tags:
    - oci

- name: Install Clearview (1.5) services
  hosts: clearview
  remote_user: "{{ eyemetric_user }}"
  become: yes

  roles:
    - role: clearview-v1_5

# NOTE: don't know what to do with this yet.
# - name: Register with RHEL play
#   #- name: Prepare GPU and Podman for FR
#   #hosts: fr_laptops
#   hosts: home
#   become: yes
#   vars:
#     subscription_username: "brightblade42"
#     subscription_password: "R2y1a1n@"
#     base_dir: "/home/eyemetric"
#     rhel_ver: {{ ansible_distribution_major_version }}
#     register_rhel: false

#   tasks:
#     # Dependencies and prerequisites setup and install
#     # This works in the lab but in prod we won't be using
#     # a dev subscription. The org may have their own
#     - name: Register RHEL installation with sub
#       community.general.redhat_subscription:
#         state: present
#         username: "{{ subscription_username }}"
#         password: "{{ subscription_password }}"
#         auto_attach: true

#   when: ansible_distribution == "RedHat"
