---
- name: Install SAFR services and dependencies.
  hosts: all
  remote_user: "{{ eyemetric_user }}"
  become: yes
  tasks:

    - name: Enable required RHEL 8 | 9 Repositories
      include_tasks: enable_rhel_repo_tasks.yml
      when: ansible_distribution == "RedHat"

    - name: dnf update RHEL
      register: dnf_update
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "RedHat"


    # Install Container requirements
    - name: Run RHEL 9 Podman tasks
      include_tasks: podman_rhel9_tasks.yml
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "9"

    - name: Run RHEL 8 Podman tasks
      include_tasks: podman_rhel8_tasks.yml
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version == "8"

    # Our actual application stuff
    - name: Run SAFR installation tasks
      include_tasks: safr_installation_tasks.yml

    - name: Run OpenSsl tasks for https only
      include_tasks: openssl_tasks.yml

    - name: Run systemd user tasks
      include_tasks: systemd_user_tasks.yml

    - name: Add a few cmd aliases for convenience to .bashrc
      blockinfile:
        path: "/home/{{ eyemetric_user }}/.bashrc"
        block: |
          alias start_fr="systemctl --user start eyemetric"
          alias stop_fr="systemctl --user stop eyemetric"
          alias stat_fr="systemctl --user status eyemetric"
