---
- name: Install SAFR services and dependencies.
  hosts: all
  remote_user: "{{ eyemetric_user }}"
  become: yes
  tasks:
    - name: RHEL based install
      include_tasks: rhel_tasks.yml
      when:
        - ansible_distribution == "RedHat"

    - name: Ubuntu based install
      include_tasks: ubuntu_tasks.yml
      when:
        - ansible_distribution == "Ubuntu"
