---
- name: Install SAFR services and dependencies.
  hosts: all
  remote_user: "{{ eyemetric_user }}"
  become: yes

  pre_tasks:
    - name: Enable RHEL 8 | 9  repos
      include_tasks: enable_rhel_repo_tasks.yml
      when: ansible_distribution == "RedHat"

  roles:
    - role: safr-v1_5
