---


# - name: Install SAFR v1.5 services and dependencies.
#   hosts: all
#   remote_user: "{{ eyemetric_user }}"
#   become: yes


#   roles:
#     - role: safr-v1_5

#   post_tasks:
#     - name: Print a message
#       debug:
#         msg: "Running post tasks for Safr Play"

- name: Install Paravision (v6) services
  hosts: paravision
  remote_user: "{{ eyemetric_user }}"
  become: yes

  roles:
    - role: paravision-v6
# ------------------------
# DATA PLAY
# ------------------------
# - name: Install initial data volumes for new installs
#   hosts: all
#   remote_user: "{{ eyemetric_user }}"
#   become: yes

#   tasks:
#     - name: Run the data tasks
#       include_tasks: tasks/dbtasks.yml

# NOTE: don't know what to do with this yet.
# - name: Register with RHEL play
#   #- name: Prepare GPU and Podman for FR
#   #hosts: fr_laptops
#   hosts: home
#   become: yes
#   vars:
#     subscription_username: "brightblade42"
#     subscription_password: "R2y1a1n@"
#     base_dir: "/home/eyemetric"
#     rhel_ver: {{ ansible_distribution_major_version }}
#     register_rhel: false

#   tasks:
#     # Dependencies and prerequisites setup and install
#     # This works in the lab but in prod we won't be using
#     # a dev subscription. The org may have their own
#     - name: Register RHEL installation with sub
#       community.general.redhat_subscription:
#         state: present
#         username: "{{ subscription_username }}"
#         password: "{{ subscription_password }}"
#         auto_attach: true

#   when: ansible_distribution == "RedHat"
