---
- name: Test some tasks before putting in main ansible
  hosts: all
  #hosts: lap
  vars:
    overwrite_data_volumes: false
  remote_user: "eyemetric"
  become: yes

  tasks:

    - name: Generate systemd unit files for safr-pod
      ansible.builtin.shell:
        cmd: 'cd /home/{{eyemetric_user}}/.config/systemd/user && podman generate systemd --new --files --name safr-pod'
      register: result
      failed_when: result.rc != 0
      tags:
        - systemd
