---
- name: Test some tasks before putting in main ansible
  hosts: all
  #hosts: lap
  vars:
    overwrite_data_volumes: false
  remote_user: "eyemetric"
  become: yes

  tasks:
    - name: check for existance of data volume
      ansible.builtin.stat:
        path: "{{ app_dir }}/data/pvdb_pgdata"
      register: data_vol

    - name: We should skip copying the data volume
      debug:
        var: data_vol
      when: data_vol.stat.exists != True or overwrite_data_volumes



