---
- name: Test some tasks before putting in main ansible
  hosts: all
  #hosts: lap
  vars:
    overwrite_data_volumes: false
  remote_user: "eyemetric"
  become: yes

  tasks:

    - name: List contents of /tmp directory
      command: ls /tmp
      register: dir_content

    - name: Display the directory content
      debug:
        var: dir_content.stdout_lines
