---
- name: rhel user creation
  block:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
      changed_when: false
    #Is passwordless necessary?
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s

    - name: create eyemetric group
      group:
        name: eyemetric
        state: present
      changed_when: false

    - name: create the non-root user to run the fr services.
      user:
        name: '{{ eyemetric_user }}'
        password: "{{ eyemetric_pwd | password_hash('sha512') }}"
        shell: /bin/bash
        groups: eyemetric
        append: yes
      changed_when: false

    - name: Add sudoers users to wheel group
      user:
        name: "{{ eyemetric_user }}"
        groups: wheel
        append: yes

    - name: Check if the local file exists
      ansible.builtin.stat:
        path: "{{ ssh_key_file }}"
      delegate_to: localhost
      register: local_file_stat

    - name: Execute task when the local file exists
      ansible.builtin.debug:
        msg: "The file exists, and the task is executed."
      when: local_file_stat.stat.exists

#    - name: Set up authorized keys for the deployer user
#      authorized_key: user="{{eyemetric_user}}" key="{{item}}"
#      with_file:
#        - "{{ ssh_key_file }}"
#      when: local_file_stat.stat.exists

  when: ansible_distribution == "RedHat"

- name: ubuntu user creation
  block:
    - name: create eyemetric user
      debug:
        msg: "No UBUNTU eyemetric users currently created. TBD"
  when: ansible_distribution == "Ubuntu"
