---
# tasks file for cuda-nvidia
---
- name: Include tasks for NVIDIA installation
  include_tasks: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version  }}.yml"
  when: "'gpu' in group_names"
