---
# tasks file for paravision-v6

---

- name: copy docker-compose template
  template:
    src: docker-compose.gpu.j2
    dest: '{{ app_dir }}/gpu/docker-compose.pv.yml'
    owner: '{{ eyemetric_user }}'
    group: '{{ eyemetric_user }}'
  when: gpu

- name: copy docker-compose template
  template:
    src: docker-compose.cpu.j2
    dest: '{{ app_dir }}/cpu/docker-compose.pv.yml'
    owner: '{{ eyemetric_user }}'
    group: '{{ eyemetric_user }}'
  when: cpu
# load tasks for the correct OS and version
- name: Include tasks for paravision installation RHEL or UBUNTU
  include_tasks: "{{ ansible_distribution }}.yml"
