---
# shh super secret

#- name: podman login so we ca pull our images
#  become: no
#  register: podman_login
#  containers.podman.podman_login:
#    username: '{{ docker_login }}'
#    password: '{{ docker_pwd }}'
#    registry: '{{ docker_registry }}'

- name: use paravisions custom registry to podman pull pv images
  become: no
  register: pv_login
  containers.podman.podman_login:
    username: '{{ pv_login }}'
    password: '{{ pv_pwd }}'
    registry: '{{ pv_registry }}'

- name: podman pull GPU based paravision containers
  become: no
  register: podman_pull
  containers.podman.podman_image:
    name: '{{ item.value }}'
    state: present
  loop: '{{ gpu_images | dict2items }}'
  when: "'gpu' in group_names"

- debug:
    var: podman_pull

- name: podman pull CPU based paravision images
  become: no
  register: podman_pull
  containers.podman.podman_image:
    name: '{{ item.value }}'
    state: present
  loop: '{{ cpu_images | dict2items }}'
  when: "'cpu' in group_names"

- name: include deploy pod tasks
  include_tasks: deploy_cpu_pv_pods.yml
  when: "'cpu' in group_names"